### ISSUE TITLE
gaussian_smoother

### ISSUE THREAD

**Issue by Fanxingye** [sagarpgs/FWISIMAT#1]
Hello，I can't find the 'gaussian_smoother' function.

**Comment by sagarpgs** [comment]
I cannot locate gaussian_smoother.m in my computer as well. As I mentioned earlier there are some codes that I lost since I developed it 4 years ago. However, I have replaced that with MATLAB's inbuilt function, which will give you similar results. Let me know if that works. I'll look into my old directories for that function and let you know if I find it.

Thank you.
